apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: cev9fdj8v-nodejs 
  janus-idp.io/tekton: cev9fdj8v-nodejs
  backstage.io/kubernetes-id: cev9fdj8v-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: cev9fdj8v-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  